name: AutoBuild
on:
  push:
    branches: ["master"]
  pull_request:
    types:
      - opened
jobs:
  build_Windows:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build src/wonderlab/wonderlab.csproj --configuration Release -p:RuntimeIdentifier=win-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: wonderlab/bin/Release/net6.0
  build_Linux:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build src/wonderlab/wonderlab.csproj --configuration Release -p:RuntimeIdentifier=linux-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: wonderlab/bin/Release/net6.0
  build_MacOS:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build src/wonderlab/wonderlab.csproj --configuration Release -p:RuntimeIdentifier=osx-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: wonderlab/bin/Release/net6.0
  build_Linux_Deb:
    runs-on:  self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet publish src/wonderlab/wonderlab.csproj -c Release -r "linux-x64" -p:PublishSingleFile="false" -p:PublishReadyToRun=true -t:CreateDeb
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux_Deb
        path: 'wonderlab/bin/Release/net6.0/linux-x64/*.deb'
  build_Linux_Rpm:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet publish src/wonderlab/wonderlab.csproj -c Release -r "linux-x64" -p:PublishSingleFile="false" -p:PublishReadyToRun=true -t:CreateRpm
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux_Rpm
        path: 'wonderlab/bin/Release/net6.0/linux-x64/*.rpm'
  build_Common:
    runs-on: [self-hosted, Windows]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build src/wonderlab/wonderlab.csproj --configuration Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Common
        path: wonderlab/bin/Release/net6.0
  Release:
    permissions: write-all
    runs-on: self-hosted
    needs: [build_Windows, build_MacOS, build_Linux_Deb, build_Linux_Rpm, build_Linux, build_Common]
    steps:
    - name: Download Windows Build
      uses: actions/download-artifact@v3
      with:
       name: Windows
       path: Release\Windows
    - name: Create Windows ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'wonderlab_Windows.zip'
         path: 'Release\Windows'
    - name: Download Linux Build
      uses: actions/download-artifact@v3
      with:
       name: Linux
       path: Release\Linux
    - name: Create Linux ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'wonderlab_Linux.zip'
         path: 'Release\Linux'
    - name: Download Deb Build
      uses: actions/download-artifact@v3
      with:
       name: Linux_Deb
    - name: Download Rpm Build
      uses: actions/download-artifact@v3
      with:
        name: Linux_Rpm
    - name: Download MacOS Build
      uses: actions/download-artifact@v3
      with:
       name: MacOS
       path: Release\MacOS
    - name: Create MacOS ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'wonderlab_MacOS.zip'
         path: 'Release\MacOS'
    - name: Download Common Build
      uses: actions/download-artifact@v3
      with:
       name: Common
       path: Release\Common
    - name: Create Common ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'wonderlab_Common.zip'
         path: 'Release\Common'
    - name: Create Release
      if: github.event_name != 'pull_request' 
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: AutoBuild
        title: "自动构建版本"
        files: |
            wonderlab_Common.zip
            wonderlab_Windows.zip
            wonderlab_Linux.zip
            wonderlab_MacOS.zip
            *.deb
            *.rpm
